"""Update WeeklyMLBPlayerStats with new Saves column

Revision ID: c38a725d49d4
Revises: 
Create Date: 2019-03-08 11:15:09.163206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38a725d49d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WeeklyMLBPlayerStats', sa.Column('saves', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WeeklyMLBPlayerStats', 'saves')
    # ### end Alembic commands ###
